<?php

function octophin_helpers_preprocess_html(&$variables)
{

    $path = \Drupal::service('path.current')->getPath();

    // Add whole path as data attribute
    $variables['attributes']['data-path'] = $path;

    // Add path as a class with / replaced with --
    $variables['attributes']['class'][] = 'page-path' . str_replace("/", "--", $path);

    $route_name = \Drupal::routeMatch()->getRouteName();

    // Add route as a class with . replaced with --
    $variables['attributes']['data-route'] = str_replace(".", "--", $route_name);
}
